DROP TABLE IF EXISTS votes CASCADE;

CREATE TABLE votes_options (
  id SERIAL PRIMARY KEY NOT NULL,
  option_id INTEGER REFERENCES options(id) NOT NULL,
  voter_id INTEGER REFERENCES votes(id) NOT NULL,
  rank VARCHAR(255) [] NOT NULL
);
